const Map<String, String> countryCodeNames = {
  '004': 'Afghanistan',
  '008': 'Albania',
  '010': 'Antarctica',
  '012': 'Algeria',
  '016': 'American Samoa',
  '020': 'Andorra',
  '024': 'Angola',
  '028': 'Antigua and Barbuda',
  '031': 'Azerbaijan',
  '032': 'Argentina',
  '036': 'Australia',
  '040': 'Austria',
  '044': 'Bahamas',
  '048': 'Bahrain',
  '050': 'Bangladesh',
  '051': 'Armenia',
  '052': 'Barbados',
  '056': 'Belgium',
  '060': 'Bermuda',
  '064': 'Bhutan',
  '068': 'Bolivia',
  '070': 'Bosnia and Herzegovina',
  '072': 'Botswana',
  '074': 'Bouvet Island',
  '076': 'Brazil',
  '084': 'Belize',
  '086': 'British Indian Ocean Territory',
  '090': 'Solomon Islands',
  '092': 'British Virgin Islands',
  '096': 'Brunei',
  '100': 'Bulgaria',
  '104': 'Myanmar',
  '108': 'Burundi',
  '112': 'Belarus',
  '116': 'Cambodia',
  '120': 'Cameroon',
  '124': 'Canada',
  '132': 'Cabo Verde',
  '136': 'Cayman Islands',
  '140': 'Central African Republic',
  '144': 'Sri Lanka',
  '148': 'Chad',
  '152': 'Chile',
  '156': 'China',
  '158': 'Taiwan',
  '162': 'Christmas Island',
  '166': 'Cocos (Keeling) Islands',
  '170': 'Colombia',
  '174': 'Comoros',
  '175': 'Mayotte',
  '178': 'Republic of the Congo',
  '180': 'Democratic Republic of the Congo',
  '184': 'Cook Islands',
  '188': 'Costa Rica',
  '191': 'Croatia',
  '192': 'Cuba',
  '196': 'Cyprus',
  '203': 'Czechia',
  '204': 'Benin',
  '208': 'Denmark',
  '212': 'Dominica',
  '214': 'Dominican Republic',
  '218': 'Ecuador',
  '222': 'El Salvador',
  '226': 'Equatorial Guinea',
  '231': 'Ethiopia',
  '232': 'Eritrea',
  '233': 'Estonia',
  '234': 'Faroe Islands',
  '238': 'Falkland Islands',
  '239': 'South Georgia and the South Sandwich Islands',
  '242': 'Fiji',
  '246': 'Finland',
  '248': 'Aland Islands',
  '250': 'France',
  '254': 'French Guiana',
  '258': 'French Polynesia',
  '260': 'French Southern Territories',
  '262': 'Djibouti',
  '266': 'Gabon',
  '268': 'Georgia',
  '270': 'Gambia',
  '275': 'Palestine',
  '276': 'Germany',
  '288': 'Ghana',
  '292': 'Gibraltar',
  '296': 'Kiribati',
  '300': 'Greece',
  '304': 'Greenland',
  '308': 'Grenada',
  '312': 'Guadeloupe',
  '316': 'Guam',
  '320': 'Guatemala',
  '324': 'Guinea',
  '328': 'Guyana',
  '332': 'Haiti',
  '334': 'Heard Island and McDonald Islands',
  '336': 'Holy See',
  '340': 'Honduras',
  '344': 'Hong Kong',
  '348': 'Hungary',
  '352': 'Iceland',
  '356': 'India',
  '360': 'Indonesia',
  '364': 'Iran',
  '368': 'Iraq',
  '372': 'Ireland',
  '376': 'Israel',
  '380': 'Italy',
  '384': "Cote d'Ivoire",
  '388': 'Jamaica',
  '392': 'Japan',
  '398': 'Kazakhstan',
  '400': 'Jordan',
  '404': 'Kenya',
  '408': 'North Korea',
  '410': 'South Korea',
  '414': 'Kuwait',
  '417': 'Kyrgyzstan',
  '418': 'Laos',
  '422': 'Lebanon',
  '426': 'Lesotho',
  '428': 'Latvia',
  '430': 'Liberia',
  '434': 'Libya',
  '438': 'Liechtenstein',
  '440': 'Lithuania',
  '442': 'Luxembourg',
  '446': 'Macao',
  '450': 'Madagascar',
  '454': 'Malawi',
  '458': 'Malaysia',
  '462': 'Maldives',
  '466': 'Mali',
  '470': 'Malta',
  '474': 'Martinique',
  '478': 'Mauritania',
  '480': 'Mauritius',
  '484': 'Mexico',
  '492': 'Monaco',
  '496': 'Mongolia',
  '498': 'Moldova',
  '499': 'Montenegro',
  '500': 'Montserrat',
  '504': 'Morocco',
  '508': 'Mozambique',
  '512': 'Oman',
  '516': 'Namibia',
  '520': 'Nauru',
  '524': 'Nepal',
  '528': 'Netherlands',
  '531': 'Curacao',
  '533': 'Aruba',
  '534': 'Sint Maarten',
  '535': 'Bonaire, Sint Eustatius and Saba',
  '540': 'New Caledonia',
  '548': 'Vanuatu',
  '554': 'New Zealand',
  '558': 'Nicaragua',
  '562': 'Niger',
  '566': 'Nigeria',
  '570': 'Niue',
  '574': 'Norfolk Island',
  '578': 'Norway',
  '580': 'Northern Mariana Islands',
  '581': 'United States Minor Outlying Islands',
  '583': 'Micronesia',
  '584': 'Marshall Islands',
  '585': 'Palau',
  '586': 'Pakistan',
  '591': 'Panama',
  '598': 'Papua New Guinea',
  '600': 'Paraguay',
  '604': 'Peru',
  '608': 'Philippines',
  '612': 'Pitcairn Islands',
  '616': 'Poland',
  '620': 'Portugal',
  '624': 'Guinea-Bissau',
  '626': 'Timor-Leste',
  '630': 'Puerto Rico',
  '634': 'Qatar',
  '638': 'Reunion',
  '642': 'Romania',
  '643': 'Russia',
  '646': 'Rwanda',
  '652': 'Saint Barthelemy',
  '654': 'Saint Helena, Ascension and Tristan da Cunha',
  '659': 'Saint Kitts and Nevis',
  '660': 'Anguilla',
  '662': 'Saint Lucia',
  '663': 'Saint Martin',
  '666': 'Saint Pierre and Miquelon',
  '670': 'Saint Vincent and the Grenadines',
  '674': 'San Marino',
  '678': 'Sao Tome and Principe',
  '682': 'Saudi Arabia',
  '686': 'Senegal',
  '688': 'Serbia',
  '690': 'Seychelles',
  '694': 'Sierra Leone',
  '702': 'Singapore',
  '703': 'Slovakia',
  '704': 'Vietnam',
  '705': 'Slovenia',
  '706': 'Somalia',
  '710': 'South Africa',
  '716': 'Zimbabwe',
  '724': 'Spain',
  '728': 'South Sudan',
  '729': 'Sudan',
  '732': 'Western Sahara',
  '740': 'Suriname',
  '744': 'Svalbard and Jan Mayen',
  '748': 'Eswatini',
  '752': 'Sweden',
  '756': 'Switzerland',
  '760': 'Syria',
  '762': 'Tajikistan',
  '764': 'Thailand',
  '768': 'Togo',
  '772': 'Tokelau',
  '776': 'Tonga',
  '780': 'Trinidad and Tobago',
  '784': 'United Arab Emirates',
  '788': 'Tunisia',
  '792': 'Turkey',
  '795': 'Turkmenistan',
  '796': 'Turks and Caicos Islands',
  '798': 'Tuvalu',
  '800': 'Uganda',
  '804': 'Ukraine',
  '807': 'North Macedonia',
  '818': 'Egypt',
  '826': 'United Kingdom',
  '831': 'Guernsey',
  '832': 'Jersey',
  '833': 'Isle of Man',
  '834': 'Tanzania',
  '840': 'United States',
  '850': 'United States Virgin Islands',
  '854': 'Burkina Faso',
  '858': 'Uruguay',
  '860': 'Uzbekistan',
  '862': 'Venezuela',
  '876': 'Wallis and Futuna',
  '882': 'Samoa',
  '887': 'Yemen',
  '894': 'Zambia',
};

const Map<String, String> countryNumericToAlpha2 = {
  '036': 'AU',
  '076': 'BR',
  '124': 'CA',
  '156': 'CN',
  '258': 'PF',
  '356': 'IN',
  '840': 'US',
};

const Map<String, String> subdivisionCodeNames = {
  'AU-ACT': 'Australian Capital Territory',
  'AU-NSW': 'New South Wales',
  'AU-NT': 'Northern Territory',
  'AU-QLD': 'Queensland',
  'AU-SA': 'South Australia',
  'AU-TAS': 'Tasmania',
  'AU-VIC': 'Victoria',
  'AU-WA': 'Western Australia',
  'BR-AC': 'Acre',
  'BR-AL': 'Alagoas',
  'BR-AM': 'Amazonas',
  'BR-AP': 'Amapa',
  'BR-BA': 'Bahia',
  'BR-CE': 'Ceara',
  'BR-DF': 'Distrito Federal',
  'BR-ES': 'Espirito Santo',
  'BR-GO': 'Goias',
  'BR-MA': 'Maranhao',
  'BR-MG': 'Minas Gerais',
  'BR-MS': 'Mato Grosso do Sul',
  'BR-MT': 'Mato Grosso',
  'BR-PA': 'Para',
  'BR-PB': 'Paraiba',
  'BR-PE': 'Pernambuco',
  'BR-PI': 'Piaui',
  'BR-PR': 'Parana',
  'BR-RJ': 'Rio de Janeiro',
  'BR-RN': 'Rio Grande do Norte',
  'BR-RO': 'Rondonia',
  'BR-RR': 'Roraima',
  'BR-RS': 'Rio Grande do Sul',
  'BR-SC': 'Santa Catarina',
  'BR-SE': 'Sergipe',
  'BR-SP': 'Sao Paulo',
  'BR-TO': 'Tocantins',
  'CA-AB': 'Alberta',
  'CA-BC': 'British Columbia',
  'CA-MB': 'Manitoba',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-NS': 'Nova Scotia',
  'CA-NT': 'Northwest Territories',
  'CA-NU': 'Nunavut',
  'CA-ON': 'Ontario',
  'CA-PE': 'Prince Edward Island',
  'CA-QC': 'Quebec',
  'CA-SK': 'Saskatchewan',
  'CA-YT': 'Yukon',
  'CN-11': 'Beijing',
  'CN-12': 'Tianjin',
  'CN-13': 'Hebei',
  'CN-14': 'Shanxi',
  'CN-15': 'Inner Mongolia',
  'CN-21': 'Liaoning',
  'CN-22': 'Jilin',
  'CN-23': 'Heilongjiang',
  'CN-31': 'Shanghai',
  'CN-32': 'Jiangsu',
  'CN-33': 'Zhejiang',
  'CN-34': 'Anhui',
  'CN-35': 'Fujian',
  'CN-36': 'Jiangxi',
  'CN-37': 'Shandong',
  'CN-41': 'Henan',
  'CN-42': 'Hubei',
  'CN-43': 'Hunan',
  'CN-44': 'Guangdong',
  'CN-45': 'Guangxi',
  'CN-46': 'Hainan',
  'CN-50': 'Chongqing',
  'CN-51': 'Sichuan',
  'CN-52': 'Guizhou',
  'CN-53': 'Yunnan',
  'CN-54': 'Tibet',
  'CN-61': 'Shaanxi',
  'CN-62': 'Gansu',
  'CN-63': 'Qinghai',
  'CN-64': 'Ningxia',
  'CN-65': 'Xinjiang',
  'PF-AU': 'Austral Islands',
  'PF-GA': 'Gambier Islands',
  'PF-MA': 'Marquesas Islands',
  'PF-SO': 'Society Islands',
  'PF-TU': 'Tuamotu Archipelago',
  'IN-AN': 'Andaman and Nicobar Islands',
  'IN-AP': 'Andhra Pradesh',
  'IN-AR': 'Arunachal Pradesh',
  'IN-AS': 'Assam',
  'IN-BR': 'Bihar',
  'IN-DL': 'Delhi',
  'IN-DN': 'Dadra and Nagar Haveli and Daman and Diu',
  'IN-GA': 'Goa',
  'IN-GJ': 'Gujarat',
  'IN-HP': 'Himachal Pradesh',
  'IN-HR': 'Haryana',
  'IN-JK': 'Jammu and Kashmir',
  'IN-KA': 'Karnataka',
  'IN-KL': 'Kerala',
  'IN-LD': 'Lakshadweep',
  'IN-MH': 'Maharashtra',
  'IN-ML': 'Meghalaya',
  'IN-OD': 'Odisha',
  'IN-PB': 'Punjab',
  'IN-TN': 'Tamil Nadu',
  'IN-WB': 'West Bengal',
  'US-AK': 'Alaska',
  'US-AL': 'Alabama',
  'US-AR': 'Arkansas',
  'US-CA': 'California',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-LA': 'Louisiana',
  'US-MA': 'Massachusetts',
  'US-MS': 'Mississippi',
  'US-NC': 'North Carolina',
  'US-NJ': 'New Jersey',
  'US-NY': 'New York',
  'US-OR': 'Oregon',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-TX': 'Texas',
  'US-VA': 'Virginia',
  'US-WA': 'Washington',
};

String _fallbackSubdivisionName(String countryCode, String subdivisionCode) {
  final alpha2 = countryNumericToAlpha2[countryCode];
  var cleaned = subdivisionCode.trim();
  if (alpha2 != null && cleaned.startsWith('$alpha2-')) {
    cleaned = cleaned.substring(alpha2.length + 1);
  }
  return cleaned.replaceAll('-', ' ');
}

String resolveCountryRegionLabel(String rawLabel) {
  final normalized = rawLabel.trim();
  if (normalized.isEmpty) return normalized;

  final parts = normalized.split(':');
  final countryCode = parts.first.padLeft(3, '0');
  final countryName = countryCodeNames[countryCode];
  if (countryName == null) return normalized;

  if (parts.length == 1) {
    return countryName;
  }

  final subdivisionCode = parts.sublist(1).join(':');
  final subdivisionName =
      subdivisionCodeNames[subdivisionCode] ??
      _fallbackSubdivisionName(countryCode, subdivisionCode);

  return '$countryName · $subdivisionName';
}
