import 'package:discere/catalog/model/external_id_provider.dart';
import 'package:discere/shared/persistence/database_helper.dart';
import 'package:sqflite/sqflite.dart';

/// Authoritative reference-DB repository for external identifiers.
///
/// These mappings are generated by the ETL and shipped inside the reference DB.
class ExternalIdRepository {
  static const tableName = 'entity_external_ids';

  final Database? _injectedRefDb;

  ExternalIdRepository({Database? referenceDatabase})
    : _injectedRefDb = referenceDatabase;

  Future<Database> get _referenceDb async =>
      _injectedRefDb ?? await DatabaseHelper.referenceDb;

  static const _batchChunkSize = 500;

  /// Returns ETL-provided taxon IDs for a batch of entities, keyed by entity ID.
  ///
  /// Only entries that parse as integers are included. Queries in chunks of
  /// [_batchChunkSize] to stay well within SQLite's 999-parameter limit.
  Future<Map<String, int>> getExternalIdsForProvider(
    Set<String> entityIds,
    ExternalIdProvider provider,
  ) async {
    if (entityIds.isEmpty) return const {};
    try {
      final db = await _referenceDb;
      final ids = entityIds.toList();
      final result = <String, int>{};
      for (var i = 0; i < ids.length; i += _batchChunkSize) {
        final chunk = ids.sublist(
          i,
          i + _batchChunkSize > ids.length ? ids.length : i + _batchChunkSize,
        );
        final placeholders = List.filled(chunk.length, '?').join(',');
        final rows = await db.rawQuery(
          'SELECT entity_id, external_id FROM $tableName '
          'WHERE provider = ? AND entity_id IN ($placeholders)',
          [provider.name, ...chunk],
        );
        for (final row in rows) {
          final id = int.tryParse(row['external_id'] as String? ?? '');
          if (id != null) result[row['entity_id'] as String] = id;
        }
      }
      return result;
    } catch (_) {
      return {};
    }
  }

  /// Returns the ETL-provided external identifier for a given entity/provider.
  Future<String?> getExternalId(
    String entityId,
    ExternalIdProvider provider,
  ) async {
    try {
      final db = await _referenceDb;
      final rows = await db.query(
        tableName,
        columns: ['external_id'],
        where: 'entity_id = ? AND provider = ?',
        whereArgs: [entityId, provider.name],
        limit: 1,
      );
      if (rows.isEmpty) return null;
      return rows.first['external_id'] as String?;
    } catch (_) {
      return null;
    }
  }

  /// Returns all ETL-provided external IDs for a given entity.
  Future<List<Map<String, dynamic>>> getExternalIds(String entityId) async {
    try {
      final db = await _referenceDb;
      return db.query(
        tableName,
        columns: [
          'entity_id',
          'entity_type',
          'provider',
          'external_id',
          'last_synced_at',
          'metadata_json',
        ],
        where: 'entity_id = ?',
        whereArgs: [entityId],
        orderBy: 'provider ASC',
      );
    } catch (_) {
      return <Map<String, dynamic>>[];
    }
  }
}
