/// Administrative subdivisions (US states, Australian territories, …),
/// English only.
///
/// Deliberately not translated: there are far more of them than countries,
/// and they are a much smaller share of what users actually pick in the
/// region filter. A code with no entry is dropped rather than shown raw.
const Map<String, String> subdivisionNames = {
  'AU-ACT': 'Australian Capital Territory',
  'AU-NSW': 'New South Wales',
  'AU-NT': 'Northern Territory',
  'AU-QLD': 'Queensland',
  'AU-SA': 'South Australia',
  'AU-TAS': 'Tasmania',
  'AU-VIC': 'Victoria',
  'AU-WA': 'Western Australia',
  'BR-AC': 'Acre',
  'BR-AL': 'Alagoas',
  'BR-AM': 'Amazonas',
  'BR-AP': 'Amapa',
  'BR-BA': 'Bahia',
  'BR-CE': 'Ceara',
  'BR-DF': 'Distrito Federal',
  'BR-ES': 'Espirito Santo',
  'BR-GO': 'Goias',
  'BR-MA': 'Maranhao',
  'BR-MG': 'Minas Gerais',
  'BR-MS': 'Mato Grosso do Sul',
  'BR-MT': 'Mato Grosso',
  'BR-PA': 'Para',
  'BR-PB': 'Paraiba',
  'BR-PE': 'Pernambuco',
  'BR-PI': 'Piaui',
  'BR-PR': 'Parana',
  'BR-RJ': 'Rio de Janeiro',
  'BR-RN': 'Rio Grande do Norte',
  'BR-RO': 'Rondonia',
  'BR-RR': 'Roraima',
  'BR-RS': 'Rio Grande do Sul',
  'BR-SC': 'Santa Catarina',
  'BR-SE': 'Sergipe',
  'BR-SP': 'Sao Paulo',
  'BR-TO': 'Tocantins',
  'CA-AB': 'Alberta',
  'CA-BC': 'British Columbia',
  'CA-MB': 'Manitoba',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-NS': 'Nova Scotia',
  'CA-NT': 'Northwest Territories',
  'CA-NU': 'Nunavut',
  'CA-ON': 'Ontario',
  'CA-PE': 'Prince Edward Island',
  'CA-QC': 'Quebec',
  'CA-SK': 'Saskatchewan',
  'CA-YT': 'Yukon',
  'CN-11': 'Beijing',
  'CN-12': 'Tianjin',
  'CN-13': 'Hebei',
  'CN-14': 'Shanxi',
  'CN-15': 'Inner Mongolia',
  'CN-21': 'Liaoning',
  'CN-22': 'Jilin',
  'CN-23': 'Heilongjiang',
  'CN-31': 'Shanghai',
  'CN-32': 'Jiangsu',
  'CN-33': 'Zhejiang',
  'CN-34': 'Anhui',
  'CN-35': 'Fujian',
  'CN-36': 'Jiangxi',
  'CN-37': 'Shandong',
  'CN-41': 'Henan',
  'CN-42': 'Hubei',
  'CN-43': 'Hunan',
  'CN-44': 'Guangdong',
  'CN-45': 'Guangxi',
  'CN-46': 'Hainan',
  'CN-50': 'Chongqing',
  'CN-51': 'Sichuan',
  'CN-52': 'Guizhou',
  'CN-53': 'Yunnan',
  'CN-54': 'Tibet',
  'CN-61': 'Shaanxi',
  'CN-62': 'Gansu',
  'CN-63': 'Qinghai',
  'CN-64': 'Ningxia',
  'CN-65': 'Xinjiang',
  'PF-AU': 'Austral Islands',
  'PF-GA': 'Gambier Islands',
  'PF-MA': 'Marquesas Islands',
  'PF-SO': 'Society Islands',
  'PF-TU': 'Tuamotu Archipelago',
  'IN-AN': 'Andaman and Nicobar Islands',
  'IN-AP': 'Andhra Pradesh',
  'IN-AR': 'Arunachal Pradesh',
  'IN-AS': 'Assam',
  'IN-BR': 'Bihar',
  'IN-DL': 'Delhi',
  'IN-DN': 'Dadra and Nagar Haveli and Daman and Diu',
  'IN-GA': 'Goa',
  'IN-GJ': 'Gujarat',
  'IN-HP': 'Himachal Pradesh',
  'IN-HR': 'Haryana',
  'IN-JK': 'Jammu and Kashmir',
  'IN-KA': 'Karnataka',
  'IN-KL': 'Kerala',
  'IN-LD': 'Lakshadweep',
  'IN-MH': 'Maharashtra',
  'IN-ML': 'Meghalaya',
  'IN-OD': 'Odisha',
  'IN-PB': 'Punjab',
  'IN-TN': 'Tamil Nadu',
  'IN-WB': 'West Bengal',
  'US-AK': 'Alaska',
  'US-AL': 'Alabama',
  'US-AR': 'Arkansas',
  'US-CA': 'California',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-LA': 'Louisiana',
  'US-MA': 'Massachusetts',
  'US-MS': 'Mississippi',
  'US-NC': 'North Carolina',
  'US-NJ': 'New Jersey',
  'US-NY': 'New York',
  'US-OR': 'Oregon',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-TX': 'Texas',
  'US-VA': 'Virginia',
  'US-WA': 'Washington',
};
