import 'package:sqflite/sqflite.dart';

import 'database_helper.dart';

/// Authoritative reference-DB repository for external identifiers.
///
/// These mappings are generated by the ETL and shipped inside the reference DB.
class ExternalIdRepository {
  static const tableName = 'entity_external_ids';

  final Database? _injectedRefDb;

  ExternalIdRepository({Database? referenceDatabase})
    : _injectedRefDb = referenceDatabase;

  Future<Database> get _referenceDb async =>
      _injectedRefDb ?? await DatabaseHelper.referenceDb;

  /// Returns the ETL-provided external identifier for a given entity/provider.
  Future<String?> getExternalId(String entityId, String provider) async {
    try {
      final db = await _referenceDb;
      final rows = await db.query(
        tableName,
        columns: ['external_id'],
        where: 'entity_id = ? AND provider = ?',
        whereArgs: [entityId, provider],
        limit: 1,
      );
      if (rows.isEmpty) return null;
      return rows.first['external_id'] as String?;
    } catch (_) {
      return null;
    }
  }

  /// Returns all ETL-provided external IDs for a given entity.
  Future<List<Map<String, dynamic>>> getExternalIds(String entityId) async {
    try {
      final db = await _referenceDb;
      return db.query(
        tableName,
        columns: [
          'entity_id',
          'entity_type',
          'provider',
          'external_id',
          'last_synced_at',
          'metadata_json',
        ],
        where: 'entity_id = ?',
        whereArgs: [entityId],
        orderBy: 'provider ASC',
      );
    } catch (_) {
      return <Map<String, dynamic>>[];
    }
  }
}
